spring.application.name=fishing

# H2 in-memory DB (resets on restart)
spring.datasource.url=jdbc:h2:mem:fishingdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 console (optional, but handy)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=DEBUG
